### ISSUE TITLE
Feature request - Make `titlex` as Nimble Publisher Plugin

### ISSUE THREAD

**Issue by kianmeng** [tverlaan/titlex#1]
Any chances of getting this into https://github.com/dashbitco/nimble_publisher as some sort of plugin? Even though right now Nimble Publisher have no support for plugins.

P/S: `titlex` is the probably the best newly published Elixir module I've read so far for the past two months.

**Comment by tverlaan** [comment]
Hi, thanks for your interest in the library :)

I think using this together with NimblePublisher should be fairly straight-forward and doesn't require a 'plugin'. NimblePublisher is compiling the posts and building it into modules. But between reading the file and compiling to a module it actually calls your own defined module in the [build option](https://hexdocs.pm/nimble_publisher/NimblePublisher.html#module-options). This is `titlex` integrated in the example from [NimblePublisher](https://hexdocs.pm/nimble_publisher/NimblePublisher.html#module-examples):

```diff
defmodule MyApp.Blog.Post do
  @enforce_keys [:id, :author, :title, :body, :description, :tags, :date]
  defstruct [:id, :author, :title, :body, :description, :tags, :date]

  def build(filename, attrs, body) do
    [year, month_day_id] = filename |> Path.rootname() |> Path.split() |> Enum.take(-2)
    [month, day, id] = String.split(month_day_id, "-", parts: 3)
    date = Date.from_iso8601!("#{year}-#{month}-#{day}")
-    struct!(__MODULE__, [id: id, date: date, body: body] ++ Map.to_list(attrs))
+    title = Title.capitalize(attrs.title)
+    attrs = Map.drop(attrs, :title)
+    struct!(__MODULE__, [id: id, date: date, body: body, title: title] ++ Map.to_list(attrs))
  end
end
```

I hope this helps :)
